#!/bin/bash
# __                      
#/\ \                     
#\ \ \____    __    _ __  
# \ \ '__`\ /'__`\ /\`'__\
#  \ \ \L\ /\ \L\.\\ \ \/ 
#   \ \_,__\ \__/.\_\ \_\ 
#    \/___/ \/__/\/_/\/_/                          
# bar - lemonbar output

clock() {
    date '+%I:%M'
}

battery() {
    BATC=/sys/class/power_supply/BAT1/capacity
    BATS=/sys/class/power_supply/BAT1/status

    test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'

    sed -n p $BATC
}

nowplaying() {
        cur=`mpc current`
          test "$1" = "scroll" && PARSER='skroll -n20 -d0.5 -r' || PARSER='cat'
          test -n "$cur" && $PARSER <<< $cur || echo "n/a"
}

npcommand() {
        echo ' %{A:mpc prev:}⏪%{A} %{A:mpc toggle:}⏯%{A} %{A:mpc next:}⏩%{A}'
}

group() {
        grp=`mgfw -g $(pfw)`
        if [[ $grp == 1 ]]
        then
                echo %{F#5f819d}⬤%{F-} ⬤ ⬤ ⬤ ⬤
        elif [[ $grp == 2 ]]
        then
                echo ⬤ %{F#5f819d}⬤%{F-} ⬤ ⬤ ⬤ 
        elif [[ $grp == 3 ]]
        then
                echo ⬤ ⬤ %{F#5f819d}⬤%{F-} ⬤ ⬤ 
        elif [[ $grp == 4 ]]
        then
                echo ⬤ ⬤ ⬤ %{F#5f819d}⬤%{F-} ⬤ 
        elif [[ $grp == 5 ]]
        then
                echo ⬤ ⬤ ⬤ ⬤ %{F#5f819d}⬤%{F-} 
        else
                echo ⬤ ⬤ ⬤ ⬤ ⬤
        fi
}

panel() {
        winname=$(wname $(pfw))
        if [ -z $winname ]
        then
                echo %{A:killw $(pfw):}%{B#cc6666}%{F#161719} ❏ %{F-}%{B-}%{A} [none]

        else
                echo %{A:killw $(pfw):}%{B#cc6666}%{F#161719} ❏ %{F-}%{B-}%{A} $winname
        fi
}

while :; do
    buf=""
    buf="${buf} %{B#f0c074}%{F#161719} ♪ %{F-}%{B-} $(nowplaying) %{B#f0c074}%{F#161719}$(npcommand)%{F-} $(panel)"
    buf="${buf} %{c}$(group)"
    buf="${buf} %{r}%{B#81a2be}%{F#161719} ⬤ %{F-}%{B-} $(clock) %{B#89c75c}%{F#161719} ☐ %{F-}%{B-} $(battery)%"

    echo $buf
done
