#!/bin/sh
#
# dytyl - dynamic tiling script
# (c) arcetera 2015 - wtfpl
#

usage() {
  echo "usage: $(basename $0) <default|full|spiral|float>"
  exit
}

# configuration

STATE_FILE=${STATE_FILE:-~/.dytyl_state}
PANEL=${PANEL:-5}
GAP=${GAP:-15}

PFW=$(pfw)
BW=$(wattr b $PFW)
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)
VERT_MASTER=$((SW/2))
HORIZ_MASTER=$((SH/2))
MAX=$(lsw|grep -v $PFW|wc -l)
SW=$((SW - GAP - 2*BW))
SH=$((SH - GAP - 2*BW - PANEL))
Y=$((0 + GAP + PANEL))
X=$((0 + GAP + PANEL)) 

full() {
  wtp $GAP $Y $((SW - GAP - 2*BW)) $((SH - GAP)) $PFW
}

fscheck() {
  if [ $(lsw | wc -l) -eq 1 ]; then
    full
    exit
  fi
}

float() {
  echo float > $STATE_FILE 
}

default() {
  echo default > $STATE_FILE 
  fscheck

  wtp $GAP $Y $((VERT_MASTER - GAP - 2*BW)) $((SH - GAP)) $PFW

  X=$((VERT_MASTER + GAP))
  W=$((SW - VERT_MASTER - GAP))
  H=$((SH / MAX - GAP - 2*BW))

  for wid in $(lsw|grep -v $PFW); do
    wtp $X $Y $W $H $wid
    Y=$((Y + H + GAP + 2*BW))
  done
}

spiral() {
  echo spiral > $STATE_FILE 
  fscheck

  wtp $GAP $Y $((VERT_MASTER - GAP - 2*BW)) $((SH - GAP)) $PFW

  X=$((VERT_MASTER + GAP))
  W=$((SW - VERT_MASTER - GAP))
  H=$((SH - GAP))

  VS=1 
  F=1

  PREV=""

  for wid in $(lsw|grep -v $PFW); do
    if [ $F -eq 1 ]; then
      F=0
      wtp $X $Y $W $H $wid
      PREV=$wid
    else
      if [ $VS -eq 1 ]; then
        VS=0
        PY=$(wattr y $PREV)
        PH=$(wattr h $PREV)
        Y=$((PY + PH/2 + GAP/2))
        wtp $X $PY $W $((PH/2 - GAP/2)) $PREV
        wtp $X $Y $W $((PH/2 - GAP/2)) $wid
        H=$(wattr h $wid)
        PREV=$wid
      else
        VS=1
        PX=$(wattr x $PREV)
        PW=$(wattr w $PREV)
        X=$((PX + PW/2 + GAP/2))
        wtp $PX $Y $((PW/2 - GAP/2)) $H $PREV
        wtp $X $Y $((PW/2 - GAP/2)) $H $wid
        W=$(wattr w $wid)
        PREV=$wid
      fi
    fi
  done
}

case $1 in
  default) default ;;
  spiral) spiral ;;
  full) full ;;
  float) float ;;
  *) usage ;;
esac
