#!/bin/sh
#
# tln - launches a terminal
# (c) arcetera 2015 - wtfpl
for terminal in $TERMINAL x-terminal-emulator urxvt rxvt terminator Eterm aterm xterm gnome-terminal roxterm xfce4-terminal st termite lxterminal mate-terminal terminology; do
    if command -v $terminal > /dev/null 2>&1; then
        exec $terminal "$@"
    fi
done

notify-send "could not find a terminal."
