#!/bin/sh
#                  __                  
#                 /\ \                 
# __  __  __   ___\ \ \___      __     
#/\ \/\ \/\ \ /'___\ \  _ `\  /'_ `\   
#\ \ \_/ \_/ /\ \__/\ \ \ \ \/\ \L\ \  
# \ \___x___/\ \____\\ \_\ \_\ \____ \ 
#  \/__//__/  \/____/ \/_/\/_/\/___L\ \
#                               /\____/
#                               \_/__/ 
# wchg - Window ChaNGe - perform actions when window status changes

while IFS=: read ev wid; do
    case $ev in
        # window creation
        16) wattr o $wid #|| dytyl default
        ;;

        # mapping requests
        19) wattr o $wid || wfw $wid
        #cw $wid
        dytyl default
        ;;

        # focus next window when deleting focused window
        18) wattr $(pfw) || wfw prev 2>/dev/null
            test -z "$(lsw)" &
            dytyl default
            ;;

        #entering window
        7) wattr o $wid || wfw $wid ;;
    esac
done
