#!/bin/sh
#
# wchg - perform actions when window status changes
# (c) arcetera 2015 - wtfpl
#

while IFS=: read ev wid; do
    case $ev in
        16) dytyl $(cat ~/.dytyl_state) ;;

        19) wattr o $wid || wfw $wid
              dytyl $(cat ~/.dytyl_state)
              ;;

        18) wattr $(pfw) || wfw prev 2>/dev/null
              [ -z "$(lsw)"] &
              dytyl $(cat ~/.dytyl_state)
              ;;

        7) wattr o $wid || wfw $wid ;;
    esac
done
