#!/bin/sh
#                             
# wfw - window focus wrapper
# (c) arcetera 2015 - wtfpl

# configuration

BW=${BW:-2}                    # border width
#BWI=${BWI:-3}                 # inner border width
#BWO=${BWO:-2}                 # outer border width
ACTIVE=${ACTIVE:-0x515151}     # active border color
INACTIVE=${INACTIVE:-0xa09f93} # inactive border color
#OUTER=${OUTER--0x393939}      # outer border color

# code

CUR=$(pfw)

usage() {
    echo "usage: $(basename $0) <next|prev|wid>" >&2
    exit 1
}

setborder() {
    ROOT=$(lsw -r)

    wattr $2 || return
    wattr o $2 && return

    [ "$(wattr xywh $2)" = "$(wattr xywh $ROOT)" ] && return

    case $1 in
        active)   chwb -s $BW -c $ACTIVE $2 ;;
        inactive) chwb -s $BW -c $INACTIVE $2 ;;
    esac
}

case $1 in
    next) wid=$(lsw|grep -v $CUR|sed '1 p;d') ;;
    prev) wid=$(lsw|grep -v $CUR|sed '$ p;d') ;;
    0x*) wattr $1 && wid=$1 ;;
    *) usage ;;
esac

[ -z "$wid" ] && { echo "$(basename $0): no window to focus" >&2; exit 1; }

chwso -r $wid           
wtf $wid                
setborder active $wid   
setborder inactive $CUR 
